blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('about/',views.AboutView.as_view(),name='about'),
    path('',views.PostListView.as_view(),name='post_list'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new/',views.PostCreateView.as_view(),name='post_new'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/remove/',views.PostDeleteView.as_view(),name='post_remove'),
    path('drafts/',views.DraftPostView.as_view(),name='post_draft_list'),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment_to_post'),
    path('comment/<int:pk>/approve/',views.approve_comment,name='approve_comment'),
    path('comment/<int:pk>/remove/',views.remove_comment,name='remove_comment'),
    path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/login/',views.LoginView.as_view(),name='login'),
    path('accounts/logout/',views.logout_then_login,name='logout')
]

blog/models.py
from django.urls import reverse
from django.utils import timezone
from django.db import models

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def approve_comments(self):
        return self.comments.filter(approved_comments=True)
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})
    
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey('blog.Post',related_name='comments',on_delete=models.CASCADE)
    author = models.CharField(max_length=128)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("blog:post_list", kwargs={"pk": self.pk})
    

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from blog.models import Post,Comment

class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('author','title','text')

    widgets = {
        'title': forms.TextInput(attrs={'class': 'textinputclass'}),
        'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'})
    }    

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author','text')

    widgets = {
        'author': forms.TextInput(attrs={'class': 'textinputclass'}),
        'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
    }     

blog/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from blog.models import Post, Comment
from blog.forms import PostForm,CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView,ListView,
DetailView,CreateView,
UpdateView,DeleteView)

# Create your views here.
class AboutView(TemplateView):
    template_name = 'blog/about.html'

class PostListView(ListView):
    redirect_field_name = 'blog:post_list'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    
class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin,CreateView):
    login_url = 'login/'
    redirect_field_name = 'blog:post_detail'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = 'login/'
    redirect_field_name = 'blog:post_detail'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

class DraftPostView(LoginRequiredMixin,ListView):    
    login_url = 'login/'
    redirect_field_name = 'blog/post_draft_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')       
        
##################################
######## FUNCTION VIEWS ##########       
##################################

@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog:post_detail',pk=post.pk)

@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail',pk=post.pk)
    else:
        form = CommentForm()
    return render(request,'blog/comment_form.html',{'form':form})    

@login_required
def approve_comment(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('blog:post_detail',pk=comment.post.pk)

@login_required
def remove_comment(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail',pk=post_pk)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>ABOUT JBLOG</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi velit maiores fuga, autem sunt pariatur reprehenderit quae quidem voluptate tenetur saepe minus quis nisi similique labore, placeat officiis provident facilis?</p>
<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum quas praesentium harum, porro perferendis suscipit quaerat accusamus aspernatur unde ipsum pariatur. Fugit nihil quisquam rem qui quasi. Perspiciatis, autem dolorum!</p>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, sunt quibusdam minima earum neque libero cum optio harum animi saepe quam quasi accusamus. Neque aliquam, explicabo nemo veniam molestias esse.</p>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JBlog</title>

    <!-- Bootstrap -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <!-- Medium Style Editor -->

    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS -->

    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">

    <!-- Fonts -->
    
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Russo+One&display=swap" rel="stylesheet">

</head>
<body>

    <!-- NAVBAR -->

    <div class="container">
        <header class="d-flex justify-content-center py-3 techfont">
          <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="navbar-brand bigbrand">JBlog</a></li>
            <li class="nav-item"><a href="{% url 'blog:about' %}" class="nav-link">About</a></li>
            <li class="nav-item"><a href="https://www.github.com" class="nav-link">Github</a></li>
            <li class="nav-item"><a href="https://www.LinkedIn.com" class="nav-link">LinkedIn</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'blog:post_new' %}" class="nav-link">New Post</a></li>
            <li class="nav-item"><a href="{% url 'blog:post_draft_list' %}" class="nav-link">Drafts</a></li>
            <li class="nav-item"><a class="nav-link">Welcome, {{user.username}}</a></li>            
            <li class="nav-item"><a href={% url 'logout' %} class="nav-link"><span class="bi bi-box-arrow-right">Logout</span></a></li>
            {% else %}
            <li class="nav-item"><a href={% url 'login' %} class="nav-link"><span class="bi bi-person"></span></a></li>
            {% endif %}
          </ul>
        </header>
      </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_posts">
            {% block content %}
            {% endblock content %}
          </div>
        </div>

      </div>
    </div>
</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>New Comment</h1>
<form class="post-form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Post Comment</button>
</form>
<script>var editor = new MediumEditor('.editable');</script>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}</p>
    <input type="submit" class="btn btn-danger" value="Delete">
</form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
  <h1 class="posttitle loader">{{ post.title }}</h1>
  {% if post.published_date %}
    <div class="date postdate">{{ post.publishe_date }}</div>
  {% else %}
    <a class="btn loader" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
  {% endif %}

  <h4 class="postcontent">{{ post.title|safe|linebreaksbr }}</h4>

  {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="bi bi-pen">Edit</span></a>
    <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="bi bi-x-square">Remove</span></a>
  {% endif %}

  <hr />
  <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

  <div class="container">
    {% for comment in post.comments.all %}
      <br />
      {% if user.is_authenticated or comment.approved_comment %}
      {{comment.created_date}}
        {% if not comment.approved_comment %}
        <a class="btn btn-primary" href="{% url 'blog:remove_comment' pk=comment.pk %}"><span class="bi bi-x-square"></span></a>
        <a class="btn btn-primary" href="{% url 'blog:approve_comment' pk=comment.pk %}"><span class="bi bi-arrow-right-square"></span></a>
        {% endif %}
        <p>{{comment.text|safe|linebreaksbr}}</p>
        <p>Posted By: {{comment.author}}</p>
      {% endif %}
      {% empty %}
      <p>No Comments!</p>
    {% endfor %}
  </div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block content %}
{% for post in posts %}
<div class="post">
    <p class="date">created: {{ post.created_date|date:d-m-Y}}</p>
    <h1><a href="{% url 'blog:post_detail' pk=post.pk %}"></a>{{post.title}}</h1>
    <p>{{post.text|truncatechars:200}}</p>
</div>
{% endfor %}
{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>New Post</h1>
<form class="post-form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
<script>var editor = new MediumEditor('.editable');</script>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
  <div class="centerstage">
    {% for post in post_list %}
    <h1 class="loader">{{post.title}}</h1>
      <div class="post">
        <h3><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h3>
        <div class="date">
            <p>Published on: {{ post.published_date|date:"D M Y" }}</p>
        </div>
        <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{post.approve_comment.count}}</a>
      </div>
    {% endfor %}
  </div>
{% endblock %}